name = "epos-create-payment-token"
type = "javascript"
main = "functions/create-payment-token.js"
# Add your Cloudflare Account ID and other settings before publishing.
# Replace with your actual account id before running `npx wrangler deploy`.
compatibility_date = "2026-04-30"